#!/usr/bin/ruby

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"

target 'SeedDatabaseExampleApp' do
  pod 'ContentfulPersistenceObjC', :path => '../../../Submodules/ContentfulPersistence'
  pod 'ContentfulDeliveryAPI', :path => '../../..'
end

